/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./components/Carousel.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImagePalette: typeof import('./components/ImagePalette.vue')['default']
    Resize: typeof import('./components/Resize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XScroll: typeof import('./components/XScroll.vue')['default']
  }
}
